In [3]:
import numpy as np
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [15]:
class Student:       
    '''一个普通的类，父类'''
    def __init__(self,a,b):    # 必须有的函数
        self.a = int(a)
        self.b = int(b)
    def add(self):    # 自定义函数
        return self.a + self.b
        
class Son(Student):    #括号里写父类的类名
    '''子类继承父类'''
    def __init__(self,a,b,c,d):
        self.c = int(c)
        self.d = int(d)
        super().__init__(a,b)    # 继承父类的公共变量
    def add_son(self):
        return self.a + self.b + self.c + self.d
        
class Qdao:
    '''掠夺：可以掠夺其他所有类'''
    def __init__(self,a,b,c,d,e,f):
        self.e = int(e)
        self.f = int(f)
        self.shai = Son(a,b,c,d)    # 掠夺 Son 类的方法
    def add_qd(self):
        return self.shai.a + self.shai.b + self.shai.c + self.shai.d + self.e + self.f
        # 注意：a,b,c,d都是未定义的，是在 shai 这个实例中的，所以要使用就要调取 shai.a,shai.b,shai.c,shai.d
        
a = input("a:")
b = input("b:")
student = Student(a,b) 
print(student.add())

c = input("c:")
d = input("d:")
son = Son(a,b,c,d)
print(son.add())
print(son.add_son())

e = input("e:")
f = input("f:")
qdao = Qdao(a,b,c,d,e,f)
print(qdao.shai.add())
print(qdao.shai.add_son())
print(qdao.add_qd())

a: 1
b: 2


3


c: 3
d: 4


3
10


e: 5
f: 6


3
10
21


In [4]:
import numpy as np
# 整数型数组和浮点型数组
arr1 = np.array([1,2,3])
arr2 = np.array([1.0,2.0,3.0])

# 同化定理
arr1[0] = 100.5
print(arr1)
arr2[0] = 100
print(arr2)
arr6 = np.linspace(1,10,5)
print(arr6)

[100   2   3]
[100.   2.   3.]
[ 1.    3.25  5.5   7.75 10.  ]


In [14]:
import numpy as np
arr1 = np.random.random((2,3))
print(arr1)
arr2 = 40 * np.random.random((2,3)) + 60
print(arr2)
arr3 = np.random.randint(1,100,(2,3))
print(arr3)
arr4 = np.random.normal(0,1,size=(2,3))
print(arr4)

[[0.4889621  0.72836562 0.29987022]
 [0.43566558 0.13305541 0.43136592]]
[[85.71395879 80.31557671 95.33711842]
 [91.77028086 85.52911768 92.07433733]]
[[22 81 88]
 [96 36  4]]
[[ 0.53540179 -0.74908549  0.03236833]
 [ 0.4240138   0.26441117  1.61566909]]


In [29]:
import numpy as np
arr1 = np.arange(1,10)
print(arr1)
print(arr1[0],arr1[-1])
arr2 = np.arange(1,10).reshape((3,3))
print(arr2) 
arr2[[0,1,2],[2,1,0]] = [10,20,30]
print(arr2)
print(arr2[:,1:3])
cut_arr = arr2[:,1]
print(cut_arr) 
cut2 = cut_arr.reshape((-1,1))
print(cut2) 

[1 2 3 4 5 6 7 8 9]
1 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2 10]
 [ 4 20  6]
 [30  8  9]]
[[ 2 10]
 [20  6]
 [ 8  9]]
[ 2 20  8]
[[ 2]
 [20]
 [ 8]]
